source 'https://rubygems.org'

gem 'capybara'
gem 'create_awesome_readme'
gem 'cucumber'
gem 'cucumber-sinatra'
gem 'database_cleaner'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'launchy'
gem 'rspec'
gem 'sinatra'
