source 'https://rubygems.org'

gem 'bcrypt-ruby'
gem 'capybara'
gem 'create_awesome_readme'
gem 'database_cleaner'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'launchy'
gem 'rack-flash3'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-partial'
